import { act, renderHook, waitFor } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { usePresentation } from '../src/hooks/usePresentation'
import { defaultPreferences, sourceRevision, type PresentationPreferences, type PresentationState } from '../src/lib/transcriptPresentation'
import { fakeBackend, makeJob } from './fakeBackend'

const defer = <T,>() => { let resolve!: (value: T) => void; let reject!: (reason: Error) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no }); return { promise, resolve, reject } }
const preference = (pause_ms: number): PresentationPreferences => ({ ...defaultPreferences(), screen: { ...defaultPreferences().screen, pause_ms } })
const saved = (revision: number, preferences: PresentationPreferences): PresentationState => ({ revision, preferences, warning: null, writable: true })
const segment = (text: string) => ({ start_ms: 0, end_ms: 100, text, speaker_id: 'A', translated_text: null })
const choose = (result: { current: ReturnType<typeof usePresentation> }, pause_ms: number) => act(() => result.current.change((p: PresentationPreferences) => ({ ...p, screen: { ...p.screen, pause_ms } })))

describe('durée de vie de la file de présentation', () => {
  it('termine la demande explicite de défauts même si la lecture revient après démontage', async () => {
    const read = defer<PresentationState>()
    const job = makeJob()
    const { backend } = fakeBackend({ loadPresentationDefaults: vi.fn(() => read.promise) })
    const view = renderHook(() => usePresentation(backend, job))
    await waitFor(() => expect(view.result.current.state).not.toBeNull())
    choose(view.result, 3500)
    act(() => { void view.result.current.saveDefaults() })
    view.unmount()
    await act(async () => { read.resolve(saved(4, defaultPreferences())) })
    await waitFor(() => expect(backend.savePresentationDefaults).toHaveBeenCalledWith(preference(3500), 4))
  })

  it('conserve l’échec des défauts après navigation et réessaie le choix original explicitement', async () => {
    const write = defer<PresentationState>()
    const { backend } = fakeBackend({ savePresentationDefaults: vi.fn()
      .mockReturnValueOnce(write.promise)
      .mockImplementation(async (p: PresentationPreferences, revision: number) => saved(revision + 1, p)) })
    const original = makeJob({ id: 'origine' })
    const other = makeJob({ id: 'autre' })
    const first = renderHook(() => usePresentation(backend, original))
    await waitFor(() => expect(first.result.current.state).not.toBeNull())
    choose(first.result, 3500)
    act(() => { void first.result.current.saveDefaults() })
    await waitFor(() => expect(backend.savePresentationDefaults).toHaveBeenCalledTimes(1))
    first.unmount()
    await act(async () => write.reject(new Error('Disque indisponible pour les défauts')))
    const next = renderHook(() => usePresentation(backend, other))
    await waitFor(() => expect(next.result.current.defaultsError).toContain('Disque indisponible'))
    expect(backend.savePresentationDefaults).toHaveBeenCalledTimes(1)
    expect(next.result.current.draft.screen.pause_ms).toBe(2000)
    act(() => next.result.current.retryDefaults())
    await waitFor(() => expect(backend.savePresentationDefaults).toHaveBeenCalledTimes(2))
    expect(backend.savePresentationDefaults).toHaveBeenLastCalledWith(preference(3500), 0)
    await waitFor(() => expect(next.result.current.defaultsStatus).toContain('sans couleurs'))
    expect(next.result.current.error).toBeNull()
    next.unmount()
  })

  it('garde le dernier brouillon lors du refresh même id et refuse la projection de l’ancienne source', async () => {
    const first = defer<PresentationState>()
    const oldPreview = defer<any>()
    const freshPreview = defer<any>()
    let refreshedRequest = false
    const original = makeJob({ segments: [segment('Ancien')] })
    const refreshed = makeJob({ segments: [segment('Nouveau')], speaker_names: { A: 'Alice' } })
    const { backend } = fakeBackend({
      savePresentation: vi.fn().mockReturnValueOnce(first.promise).mockImplementation(async (_id: string, p: PresentationPreferences, r: number) => saved(r + 1, p)),
      previewPresentation: vi.fn().mockReturnValueOnce(oldPreview.promise).mockImplementation(async (_id, options) => refreshedRequest ? freshPreview.promise : ({ schema_version: 1, job_id: original.id, source_revision: await sourceRevision(original), options, blocks: [{ segment_indices: [0], start_ms: 0, end_ms: 100, speaker_id: 'A' }] })),
    })
    const { result, rerender } = renderHook(({ job }) => usePresentation(backend, job), { initialProps: { job: original } })
    await waitFor(() => expect(backend.previewPresentation).toHaveBeenCalledTimes(1))
    choose(result, 3000)
    await waitFor(() => expect(backend.savePresentation).toHaveBeenCalledTimes(1))
    choose(result, 3500)
    refreshedRequest = true
    rerender({ job: refreshed })
    expect(result.current.draft.screen.pause_ms).toBe(3500)
    await act(async () => oldPreview.resolve({ schema_version: 1, job_id: original.id, source_revision: await sourceRevision(original), options: defaultPreferences().screen, blocks: [{ segment_indices: [0], start_ms: 0, end_ms: 100, speaker_id: 'A' }] }))
    expect(result.current.snapshot).toBeNull()
    await act(async () => freshPreview.resolve({ schema_version: 1, job_id: refreshed.id, source_revision: await sourceRevision(refreshed), options: preference(3500).screen, blocks: [{ segment_indices: [0], start_ms: 0, end_ms: 100, speaker_id: 'A' }] }))
    expect(result.current.snapshot?.source_revision).toBe(await sourceRevision(refreshed))
    await act(async () => first.resolve(saved(1, preference(3000))))
    await waitFor(() => expect(backend.savePresentation).toHaveBeenCalledTimes(2))
    expect(backend.savePresentation).toHaveBeenLastCalledWith(original.id, preference(3500), 1)
    await waitFor(() => expect(result.current.snapshot?.source_revision).toBeDefined())
    expect(result.current.snapshot?.source_revision).toBe(await sourceRevision(refreshed))
  })

  it('réutilise la file au remontage immédiat sans relire le disque périmé', async () => {
    const first = defer<PresentationState>()
    const job = makeJob()
    const { backend } = fakeBackend({ savePresentation: vi.fn().mockReturnValueOnce(first.promise).mockImplementation(async (_id: string, p: PresentationPreferences, r: number) => saved(r + 1, p)) })
    const mounted = renderHook(() => usePresentation(backend, job))
    await waitFor(() => expect(mounted.result.current.state).not.toBeNull())
    choose(mounted.result, 3000)
    await waitFor(() => expect(backend.savePresentation).toHaveBeenCalledTimes(1))
    choose(mounted.result, 3500)
    mounted.unmount()
    const next = renderHook(() => usePresentation(backend, job))
    await waitFor(() => expect(next.result.current.draft.screen.pause_ms).toBe(3500))
    expect(backend.loadPresentation).toHaveBeenCalledTimes(1)
    await act(async () => first.resolve(saved(1, preference(3000))))
    await waitFor(() => expect(next.result.current.state?.revision).toBe(2))
    expect(next.result.current.draft.screen.pause_ms).toBe(3500)
    next.unmount()
  })

  it('finit la file de l’ancien id après navigation sans appliquer son retour au nouveau', async () => {
    const first = defer<PresentationState>()
    const original = makeJob({ id: 'ancien' })
    const next = makeJob({ id: 'nouveau' })
    const { backend } = fakeBackend({ savePresentation: vi.fn().mockReturnValueOnce(first.promise).mockImplementation(async (_id: string, p: PresentationPreferences, r: number) => saved(r + 1, p)) })
    const view = renderHook(({ job }) => usePresentation(backend, job), { initialProps: { job: original } })
    await waitFor(() => expect(view.result.current.state).not.toBeNull())
    choose(view.result, 3000)
    await waitFor(() => expect(backend.savePresentation).toHaveBeenCalledTimes(1))
    choose(view.result, 3500)
    view.rerender({ job: next })
    await waitFor(() => expect(view.result.current.state).not.toBeNull())
    await act(async () => first.resolve(saved(1, preference(3000))))
    await waitFor(() => expect(backend.savePresentation).toHaveBeenCalledTimes(2))
    expect(backend.savePresentation).toHaveBeenLastCalledWith('ancien', preference(3500), 1)
    expect(view.result.current.draft.screen.pause_ms).toBe(2000)
    expect(view.result.current.state?.revision).toBe(0)
  })

  it('expose au remontage l’erreur après démontage et attend un retry explicite', async () => {
    const first = defer<PresentationState>()
    const job = makeJob()
    const { backend } = fakeBackend({ savePresentation: vi.fn().mockReturnValueOnce(first.promise).mockImplementation(async (_id: string, p: PresentationPreferences, r: number) => saved(r + 1, p)) })
    const view = renderHook(() => usePresentation(backend, job))
    await waitFor(() => expect(view.result.current.state).not.toBeNull())
    choose(view.result, 3000)
    await waitFor(() => expect(backend.savePresentation).toHaveBeenCalledTimes(1))
    choose(view.result, 3500)
    view.unmount()
    await act(async () => first.reject(new Error('Disque indisponible')))
    const next = renderHook(() => usePresentation(backend, job))
    await waitFor(() => expect(next.result.current.error).toContain('Disque indisponible'))
    expect(next.result.current.draft.screen.pause_ms).toBe(3500)
    expect(backend.savePresentation).toHaveBeenCalledTimes(1)
    act(() => next.result.current.retry())
    await waitFor(() => expect(next.result.current.state?.revision).toBe(1))
    expect(backend.savePresentation).toHaveBeenLastCalledWith(job.id, preference(3500), 0)
    next.unmount()
  })
})
