import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it, vi } from 'vitest'
import { TranscriptExplorer } from '../src/components/TranscriptExplorer'
import { makeJob } from './fakeBackend'

const passage = (text: string, start_ms: number, end_ms = start_ms + 1000) => ({ text, start_ms, end_ms, speaker_id: 'A', translated_text: null })

describe('lecteur de transcription', () => {
  it('conserve le fil complet et navigue toutes les occurrences sans lancer le média', async () => {
    const user = userEvent.setup()
    render(<TranscriptExplorer job={makeJob({ segments: [passage('Été été', 0), passage('été', 1000)] })} translated={false} />)
    expect(screen.getByText('Lecture audio pas encore disponible.')).toBeInTheDocument()
    await user.type(screen.getByRole('searchbox', { name: /rechercher/i }), 'ete')
    await screen.findByText('1 / 3')
    expect(screen.getAllByText('été', { selector: 'mark' })).toHaveLength(2)
    await user.click(screen.getByRole('button', { name: /occurrence suivante/i }))
    expect(screen.getByText('2 / 3')).toBeInTheDocument()
    fireEvent.keyDown(screen.getByRole('searchbox'), { key: 'Enter', shiftKey: true })
    expect(screen.getByText('1 / 3')).toBeInTheDocument()
    fireEvent.keyDown(document, { key: 'f', ctrlKey: true })
    expect(screen.getByRole('searchbox')).toHaveFocus()
    await user.click(screen.getByRole('button', { name: /occurrence précédente/i }))
    expect(screen.getByText('3 / 3')).toBeInTheDocument()
    expect(screen.queryByRole('audio')).not.toBeInTheDocument()
    expect(screen.getAllByRole('button', { name: /écouter ce passage/i })[0]).toBeDisabled()
    await user.clear(screen.getByRole('searchbox'))
    await user.type(screen.getByRole('searchbox'), 'introuvable')
    await screen.findByText(/aucune occurrence/i)
    expect(screen.getByText('0 / 0')).toBeInTheDocument()
    expect(screen.getByText(/aucune occurrence/i)).toBeInTheDocument()
  })
  it('saute à un résultat absolu en paginant sans rendre vingt mille lignes', async () => {
    const segments = Array.from({ length: 20001 }, (_, i) => passage(i === 17555 ? 'cible' : `passage ${i}`, i * 1000))
    render(<TranscriptExplorer job={makeJob({ segments })} translated={false} />)
    expect(document.querySelectorAll('.segment')).toHaveLength(100)
    await userEvent.setup().type(screen.getByRole('searchbox'), 'cible')
    await waitFor(() => expect(screen.getByText(/17501–17600 sur 20001/)).toBeInTheDocument(), { timeout: 10000 })
    expect(screen.getByText('cible')).toBeInTheDocument()
    expect(document.querySelectorAll('.segment')).toHaveLength(100)
    expect(screen.getByText(/17501–17600 sur 20001/)).toBeInTheDocument()
  })
  it('ne remplace pas silencieusement une traduction manquante par l’original', () => {
    render(<TranscriptExplorer job={makeJob({ segments: [passage('Original unique', 0)] })} translated />)
    expect(screen.getByText('[traduction manquante]')).toBeInTheDocument()
    expect(screen.queryByText('Original unique')).not.toBeInTheDocument()
  })
  it('écoute un passage avec contexte sans déplacer le média en changeant de résultat', async () => {
    const play = vi.spyOn(HTMLMediaElement.prototype, 'play').mockResolvedValue()
    const job = makeJob({ segments: [passage('mot mot', 7000), passage('mot', 9000)] })
    const { container } = render(<TranscriptExplorer job={job} translated={false} playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 5000, durationMs: 30000 }} />)
    const audio = container.querySelector('audio')!
    await userEvent.setup().type(screen.getByRole('searchbox'), 'mot')
    expect(audio.currentTime).toBe(0)
    await screen.findByText('1 / 3')
    await userEvent.setup().click(screen.getAllByRole('button', { name: /écouter ce passage/i })[0])
    expect(audio.currentTime).toBe(0)
    expect(play).toHaveBeenCalledOnce()
    await userEvent.setup().click(screen.getByRole('button', { name: /occurrence suivante/i }))
    expect(audio.currentTime).toBe(0)
    fireEvent.timeUpdate(audio, { target: { currentTime: 4.5 } })
    expect(within(container.querySelectorAll('.segment')[1] as HTMLElement).getByText('mot')).toBeInTheDocument()
    play.mockRestore()
  })
  it('le suivi facultatif révèle le passage lu même pendant une recherche filtrée', async () => {
    const job = makeJob({ segments: [passage('mot', 5000), passage('autre', 7000)] })
    const { container } = render(<TranscriptExplorer job={job} translated={false} playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 5000, durationMs: 10000 }} />)
    await userEvent.setup().type(screen.getByRole('searchbox'), 'mot')
    await screen.findByText('1 / 1')
    expect(screen.getByText('autre')).toBeInTheDocument()
    await userEvent.setup().click(screen.getByLabelText('Suivre la lecture'))
    const audio = container.querySelector('audio')!
    audio.currentTime = 2.5
    fireEvent.timeUpdate(audio)
    expect(screen.getByText('autre').closest('li')).toHaveClass('segment--playing')
  })
  it('attend les métadonnées avant de poser la tête de lecture et remet le temps à zéro au changement de source', async () => {
    const play = vi.spyOn(HTMLMediaElement.prototype, 'play').mockResolvedValue()
    const job = makeJob({ segments: [passage('essai', 15000)] })
    const first = { src: 'blob:fiction-a', timelineOffsetMs: 5000, durationMs: 30000 }
    const { container, rerender } = render(<TranscriptExplorer job={job} translated={false} playbackSource={first} />)
    const audio = container.querySelector('audio')!
    await userEvent.setup().click(screen.getByRole('button', { name: /écouter ce passage/i }))
    expect(audio.currentTime).toBe(0)
    fireEvent.loadedMetadata(audio)
    expect(audio.currentTime).toBe(8)
    rerender(<TranscriptExplorer job={job} translated={false} playbackSource={{ ...first, src: 'blob:fiction-b' }} />)
    expect(screen.getByText('00:00:05')).toBeInTheDocument()
    play.mockRestore()
  })
  it('ignore un rejet tardif de l’ancienne source', async () => {
    let reject!: (error: Error) => void
    const play = vi.spyOn(HTMLMediaElement.prototype, 'play').mockImplementation(() => new Promise((_resolve, fail) => { reject = fail }))
    const source = { src: 'blob:fiction-a', timelineOffsetMs: 0, durationMs: 10000 }
    const { rerender } = render(<TranscriptExplorer job={makeJob({ segments: [passage('essai', 5000)] })} translated={false} playbackSource={source} />)
    fireEvent.click(screen.getByRole('button', { name: 'Lire' }))
    rerender(<TranscriptExplorer job={makeJob({ segments: [passage('essai', 5000)] })} translated={false} playbackSource={{ ...source, src: 'blob:fiction-b' }} />)
    await act(async () => { reject(new Error('ancienne source')) })
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    play.mockRestore()
  })
  it('signale un rejet de lecture et marque simultanément les passages chevauchants', async () => {
    const pause = vi.spyOn(HTMLMediaElement.prototype, 'pause').mockImplementation(() => {})
    const play = vi.spyOn(HTMLMediaElement.prototype, 'play').mockRejectedValue(new Error('non autorisé'))
    const job = makeJob({ segments: [passage('un', 5000, 9000), passage('deux', 6000, 8000)] })
    const { container } = render(<TranscriptExplorer job={job} translated={false} playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 5000, durationMs: 10000 }} />)
    await userEvent.setup().click(screen.getAllByRole('button', { name: /écouter ce passage/i })[0])
    expect(await screen.findByRole('alert')).toHaveTextContent('Lecture impossible')
    const audio = container.querySelector('audio')!
    audio.currentTime = 1.5
    fireEvent.timeUpdate(audio)
    expect(container.querySelectorAll('.segment--playing')).toHaveLength(2)
    play.mockRestore(); pause.mockRestore()
  })
  it('révèle la deuxième marque sans déplacer le média et garde le fil', async () => {
    const scroll = vi.fn()
    HTMLElement.prototype.scrollIntoView = scroll
    const job = makeJob({ segments: [passage('mot mot', 0), passage('ailleurs', 1000), passage('troisième', 2000)] })
    const { container } = render(<TranscriptExplorer job={job} translated={false} playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 0, durationMs: 3000 }} />)
    await userEvent.setup().type(screen.getByRole('searchbox'), 'mot')
    await screen.findByText('1 / 2')
    expect(container.querySelectorAll('.segment')).toHaveLength(3)
    await userEvent.setup().click(screen.getByLabelText('N’afficher que les résultats'))
    expect(container.querySelectorAll('.segment')).toHaveLength(1)
    await userEvent.setup().click(screen.getByLabelText('N’afficher que les résultats'))
    expect(container.querySelectorAll('.segment')).toHaveLength(3)
    scroll.mockClear()
    await userEvent.setup().click(screen.getByRole('button', { name: 'Occurrence suivante' }))
    expect(scroll).toHaveBeenCalledTimes(1)
    expect(scroll.mock.instances[0]).toBe(container.querySelectorAll('mark')[1])
    expect(container.querySelector('audio')!.currentTime).toBe(0)
  })
  it('suit une seule fois par passage puis suspend après scroll manuel', async () => {
    const scroll = vi.fn()
    HTMLElement.prototype.scrollIntoView = scroll
    const job = makeJob({ segments: [passage('un', 0), passage('deux', 1000), passage('trois', 2000)] })
    const { container } = render(<TranscriptExplorer job={job} translated={false} playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 0, durationMs: 3000 }} />)
    await userEvent.setup().click(screen.getByLabelText('Suivre la lecture'))
    const audio = container.querySelector('audio')!
    expect(scroll).toHaveBeenCalledTimes(1)
    expect(scroll.mock.instances[0]).toBe(container.querySelectorAll('.segment')[0])
    scroll.mockClear()
    audio.currentTime = 1.1; fireEvent.timeUpdate(audio)
    audio.currentTime = 1.2; fireEvent.timeUpdate(audio)
    expect(scroll).toHaveBeenCalledTimes(1)
    fireEvent.wheel(container.querySelector('.transcript')!)
    audio.currentTime = 2.1; fireEvent.timeUpdate(audio)
    expect(scroll).toHaveBeenCalledTimes(1)
    await userEvent.setup().click(screen.getByRole('button', { name: 'Revenir à la lecture' }))
    expect(scroll).toHaveBeenCalledTimes(2)
    expect(scroll.mock.instances[1]).toBe(container.querySelectorAll('.segment')[2])
  })
  it('révèle de nouveau une occurrence unique quand la navigation reboucle dessus', async () => {
    const previous = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'scrollIntoView')
    const scroll = vi.fn()
    Object.defineProperty(HTMLElement.prototype, 'scrollIntoView', { configurable: true, value: scroll })
    try {
      render(<TranscriptExplorer job={makeJob({ segments: [passage('réponse unique', 0)] })} translated={false} />)
      const user = userEvent.setup()
      await user.type(screen.getByLabelText('Rechercher dans la transcription'), 'unique')
      expect(await screen.findByText('1 / 1')).toBeInTheDocument()
      scroll.mockClear()
      await user.click(screen.getByLabelText('Occurrence suivante'))
      expect(scroll).toHaveBeenCalledTimes(1)
      await user.click(screen.getByLabelText('Occurrence précédente'))
      expect(scroll).toHaveBeenCalledTimes(2)
    } finally {
      if (previous) Object.defineProperty(HTMLElement.prototype, 'scrollIntoView', previous)
      else Reflect.deleteProperty(HTMLElement.prototype, 'scrollIntoView')
    }
  })
  it.each([[300, -62], [0, -2]])('garde l’en-tête du passage visible si le mot peut tenir avec lui (%i)', async (segmentTop, adjustment) => {
    const previousHeight = Object.getOwnPropertyDescriptor(globalThis, 'innerHeight')
    Object.defineProperty(globalThis, 'innerHeight', { configurable: true, writable: true, value: 600 })
    const original = HTMLElement.prototype.getBoundingClientRect
    const measure = vi.spyOn(HTMLElement.prototype, 'getBoundingClientRect').mockImplementation(function (this: HTMLElement) {
      if (this.classList.contains('explorer__tools')) return new DOMRect(0, 65, 600, 285)
      if (this.classList.contains('segment')) return new DOMRect(0, segmentTop, 600, 500)
      if (this.classList.contains('transcript-mark--current')) return new DOMRect(0, 360, 50, 18)
      return original.call(this)
    })
    const scroll = vi.spyOn(window, 'scrollBy').mockImplementation(() => {})
    try {
      render(<TranscriptExplorer job={makeJob({ segments: [passage('cible', 0)] })} translated={false} />)
      await userEvent.setup().type(screen.getByLabelText('Rechercher dans la transcription'), 'cible')
      expect(await screen.findByText('1 / 1')).toBeInTheDocument()
      expect(scroll).toHaveBeenLastCalledWith({ top: adjustment, behavior: 'instant' })
    } finally {
      scroll.mockRestore()
      measure.mockRestore()
      if (previousHeight) Object.defineProperty(globalThis, 'innerHeight', previousHeight)
      else Reflect.deleteProperty(globalThis, 'innerHeight')
    }
  })
  it('pagine les seuls résultats sans pages vides entre des passages éloignés', async () => {
    const job = makeJob({ segments: Array.from({ length: 305 }, (_, i) => passage(i === 2 || i === 202 ? 'cible' : `neutre ${i}`, i * 1000)) })
    const { container } = render(<TranscriptExplorer job={job} translated={false} />)
    const user = userEvent.setup()
    await user.type(screen.getByLabelText('Rechercher dans la transcription'), 'cible')
    expect(await screen.findByText('1 / 2')).toBeInTheDocument()
    await user.click(screen.getByLabelText('N’afficher que les résultats'))
    expect([...container.querySelectorAll('.segment')].map(e => e.getAttribute('data-segment-index'))).toEqual(['2', '202'])
    expect(screen.queryByRole('button', { name: 'Page suivante' })).not.toBeInTheDocument()
    await user.click(screen.getByLabelText('Occurrence suivante'))
    expect(screen.getByText('2 / 2')).toBeInTheDocument()
    expect(container.querySelector('.transcript-mark--current')?.closest('.segment')).toHaveAttribute('data-segment-index', '202')
    await user.click(screen.getByLabelText('N’afficher que les résultats'))
    expect(container.querySelectorAll('.segment')).toHaveLength(100)
    expect(container.querySelector('.segment')).toHaveAttribute('data-segment-index', '200')
    expect(container.querySelector('.transcript-mark--current')?.closest('.segment')).toHaveAttribute('data-segment-index', '202')
  })
  it('conserve la limite de cent passages quand les résultats seuls ont plusieurs pages', async () => {
    const matching = Array.from({ length: 101 }, (_, i) => i * 2)
    const job = makeJob({ segments: Array.from({ length: 205 }, (_, i) => passage(matching.includes(i) ? 'cible' : 'neutre', i * 1000)) })
    const { container } = render(<TranscriptExplorer job={job} translated={false} />)
    const user = userEvent.setup()
    await user.type(screen.getByLabelText('Rechercher dans la transcription'), 'cible')
    expect(await screen.findByText('1 / 101')).toBeInTheDocument()
    await user.click(screen.getByLabelText('N’afficher que les résultats'))
    expect(container.querySelectorAll('.segment')).toHaveLength(100)
    expect(screen.getByText('1–100 sur 101')).toBeInTheDocument()
    await user.click(within(screen.getByRole('navigation', { name: 'Pages de transcription' })).getByRole('button', { name: 'Page suivante' }))
    expect(container.querySelectorAll('.segment')).toHaveLength(1)
    expect(container.querySelector('.segment')).toHaveAttribute('data-segment-index', '200')
    expect(screen.getByText('101–101 sur 101')).toBeInTheDocument()
  })
  it.each(['retour', 'réactivation'])('revient à la page audio éloignée après filtrage (%s)', async mode => {
    const job = makeJob({ segments: Array.from({ length: 305 }, (_, i) => passage(i === 2 ? 'cible' : 'neutre', i * 1000)) })
    const { container } = render(<TranscriptExplorer job={job} translated={false} playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 0, durationMs: 305000 }} />)
    const user = userEvent.setup()
    const media = container.querySelector('audio')!
    await user.click(screen.getByLabelText('Suivre la lecture'))
    media.currentTime = 202.2
    fireEvent.timeUpdate(media)
    expect(container.querySelector('.segment--playing')).toHaveAttribute('data-segment-index', '202')
    if (mode === 'réactivation') await user.click(screen.getByLabelText('Suivre la lecture'))
    await user.type(screen.getByLabelText('Rechercher dans la transcription'), 'cible')
    expect(await screen.findByText('1 / 1')).toBeInTheDocument()
    await user.click(screen.getByLabelText('N’afficher que les résultats'))
    expect(container.querySelectorAll('.segment')).toHaveLength(1)
    if (mode === 'retour') await user.click(screen.getByRole('button', { name: 'Revenir à la lecture' }))
    else await user.click(screen.getByLabelText('Suivre la lecture'))
    expect(screen.getByLabelText('N’afficher que les résultats')).not.toBeChecked()
    expect(container.querySelector('.segment')).toHaveAttribute('data-segment-index', '200')
    expect(container.querySelector('.segment--playing')).toHaveAttribute('data-segment-index', '202')
    expect(media.currentTime).toBe(202.2)
    fireEvent.timeUpdate(media)
    expect(container.querySelector('.segment--playing')).toHaveAttribute('data-segment-index', '202')
  })
  it('suspend le suivi quand une recherche est saisie sans déplacer l’audio', async () => {
    const job = makeJob({ segments: [passage('introduction', 0), passage('cible', 2000)] })
    const { container } = render(<TranscriptExplorer job={job} translated={false} playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 0, durationMs: 5000 }} />)
    const user = userEvent.setup()
    const audio = container.querySelector('audio')!
    audio.currentTime = 0.2
    await user.click(screen.getByLabelText('Suivre la lecture'))
    await user.type(screen.getByLabelText('Rechercher dans la transcription'), 'cible')
    expect(await screen.findByText('1 / 1')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Revenir à la lecture' })).toBeInTheDocument()
    expect(audio.currentTime).toBe(0.2)
  })
  it('respecte le filtre pendant le suivi et restaure le contexte au retour à la lecture', async () => {
    const job = makeJob({ segments: [passage('introduction', 0), passage('cible recherchée', 2000), passage('conclusion', 4000)] })
    const { container } = render(<TranscriptExplorer job={job} translated={false} playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 0, durationMs: 6000 }} />)
    const user = userEvent.setup()
    await user.type(screen.getByLabelText('Rechercher dans la transcription'), 'cible')
    expect(await screen.findByText('1 / 1')).toBeInTheDocument()
    await user.click(screen.getByLabelText('Suivre la lecture'))
    await user.click(screen.getByLabelText('N’afficher que les résultats'))
    expect(container.querySelectorAll('.segment')).toHaveLength(1)
    expect(container.querySelector('.segment')).toHaveAttribute('data-segment-index', '1')
    const audio = container.querySelector('audio')!
    audio.currentTime = 4.2
    fireEvent.timeUpdate(audio)
    expect(container.querySelectorAll('.segment')).toHaveLength(1)
    await user.click(screen.getByRole('button', { name: 'Revenir à la lecture' }))
    expect(screen.getByLabelText('N’afficher que les résultats')).not.toBeChecked()
    expect(container.querySelectorAll('.segment')).toHaveLength(3)
    expect(container.querySelector('.segment--playing')).toHaveAttribute('data-segment-index', '2')
  })
  it('arrête et remet au début un autre travail partageant la même URL, sans perdre la vitesse', async () => {
    const pause = vi.spyOn(HTMLMediaElement.prototype, 'pause').mockImplementation(() => {})
    const job = makeJob({ segments: [passage('mot', 0)] })
    const src = { src: 'blob:meme', timelineOffsetMs: 0, durationMs: 10000 }
    const { container, rerender } = render(<TranscriptExplorer job={job} translated={false} playbackSource={src} />)
    await userEvent.setup().selectOptions(screen.getByLabelText('Vitesse de lecture'), '1.5')
    const audio = container.querySelector('audio')!
    expect(audio.playbackRate).toBe(1.5)
    Object.defineProperty(audio, 'readyState', { configurable: true, value: 4 })
    audio.currentTime = 4.2
    fireEvent.timeUpdate(audio)
    fireEvent.play(audio)
    rerender(<TranscriptExplorer job={{ ...job, id: 'autre' }} translated={false} playbackSource={src} />)
    expect(pause).toHaveBeenCalled()
    expect(audio.currentTime).toBe(0)
    expect(screen.getByText('00:00:00')).toBeInTheDocument()
    expect(audio.playbackRate).toBe(1.5)
    pause.mockRestore()
  })
  it('identifie l’audio original sous traduction et réduit un compteur devenu obsolète', async () => {
    const job = makeJob({ segments: [{ ...passage('mot mot', 0), translated_text: 'salut salut' }] })
    const { rerender } = render(<TranscriptExplorer job={job} translated playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 0, durationMs: 3000 }} />)
    expect(screen.getByText('Audio original')).toBeInTheDocument()
    await userEvent.setup().type(screen.getByRole('searchbox'), 'salut')
    await screen.findByText('1 / 2')
    await userEvent.setup().click(screen.getByRole('button', { name: 'Occurrence suivante' }))
    expect(screen.getByText('2 / 2')).toBeInTheDocument()
    rerender(<TranscriptExplorer job={{ ...job, segments: [{ ...job.segments[0], translated_text: 'salut autre' }] }} translated playbackSource={{ src: 'blob:fiction', timelineOffsetMs: 0, durationMs: 3000 }} />)
    await screen.findByText('1 / 1')
  })
})
