LangString addOrReinstall ${LANG_FRENCH} "Ajouter ou réinstaller un composant."
LangString alreadyInstalled ${LANG_FRENCH} "Déjà installé."
LangString alreadyInstalledLong ${LANG_FRENCH} "${PRODUCTNAME} ${VERSION} est déjà installé. Choisissez une opération, puis cliquez sur Suivant."
LangString appRunning ${LANG_FRENCH} "{{product_name}} est en cours d'exécution. Fermez l'application avant de réessayer."
LangString appRunningOkKill ${LANG_FRENCH} "{{product_name}} est en cours d'exécution.$\nCliquez sur OK pour fermer l'application."
LangString chooseMaintenanceOption ${LANG_FRENCH} "Choisissez l'opération de maintenance à effectuer."
LangString choowHowToInstall ${LANG_FRENCH} "Choisissez l'emplacement d'installation de ${PRODUCTNAME}."
LangString createDesktop ${LANG_FRENCH} "Créer un raccourci sur le bureau."
LangString dontUninstall ${LANG_FRENCH} "Ne pas désinstaller"
LangString dontUninstallDowngrade ${LANG_FRENCH} "Ne pas désinstaller (l'installation d'une ancienne version sans désinstallation préalable est désactivée)."
LangString failedToKillApp ${LANG_FRENCH} "Impossible de fermer {{product_name}}. Fermez l'application, puis réessayez."
LangString installingWebview2 ${LANG_FRENCH} "Installation de WebView2..."
LangString newerVersionInstalled ${LANG_FRENCH} "Une version plus récente de ${PRODUCTNAME} est déjà installée. Désinstallez-la avant de revenir à une ancienne version. Choisissez une opération, puis cliquez sur Suivant."
LangString older ${LANG_FRENCH} "ancienne"
LangString olderOrUnknownVersionInstalled ${LANG_FRENCH} "La version $R4 de ${PRODUCTNAME} est installée. Il est recommandé de la désinstaller d'abord. Choisissez une opération, puis cliquez sur Suivant."
LangString silentDowngrades ${LANG_FRENCH} "Le retour à une ancienne version est désactivé pour l'installation silencieuse. Utilisez l'interface graphique.$\n"
LangString unableToUninstall ${LANG_FRENCH} "Impossible de désinstaller le programme !"
LangString uninstallApp ${LANG_FRENCH} "Désinstaller ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_FRENCH} "Désinstaller avant d'installer"
LangString unknown ${LANG_FRENCH} "inconnu"
LangString webview2AbortError ${LANG_FRENCH} "L'installation de WebView2 a échoué. L'application ne peut pas fonctionner sans ce composant. Redémarrez l'installation."
LangString webview2DownloadError ${LANG_FRENCH} "Erreur : le téléchargement de WebView2 a échoué - $0"
LangString webview2DownloadSuccess ${LANG_FRENCH} "WebView2 a été téléchargé."
LangString webview2Downloading ${LANG_FRENCH} "Téléchargement de WebView2..."
LangString webview2InstallError ${LANG_FRENCH} "Erreur : l'installation de WebView2 a échoué (code $1)."
LangString webview2InstallSuccess ${LANG_FRENCH} "WebView2 a été installé."
LangString deleteAppData ${LANG_FRENCH} "Supprimer les données de l'application"
